### ISSUE TITLE
JSON data not necessarily loaded

### ISSUE THREAD

**Issue by 1j01** [ijkilchenko/Fuzbal#28]
Initially this extension didn't work, and there were no error messages in the popup.
Later I checked the background page and found these errors:

```
_generated_background_page.html:1 Error in event handler for (unknown): TypeError: Cannot use 'in' operator to search for 'skip' in undefined
    at subset (chrome-extension://lidjpicdkcgjdkgifmmpalkibjeppdof/background.js:20:18)
    at chrome-extension://lidjpicdkcgjdkgifmmpalkibjeppdof/background.js:28:24
3_generated_background_page.html:1 Error in event handler for (unknown): TypeError: Cannot use 'in' operator to search for 'menu' in undefined
    at subset (chrome-extension://lidjpicdkcgjdkgifmmpalkibjeppdof/background.js:20:18)
    at chrome-extension://lidjpicdkcgjdkgifmmpalkibjeppdof/background.js:28:24
```

`subset(msg.words, vectors)` fails if `vectors` is not yet loaded.

**Comment by ijkilchenko** [comment]
What page were you browsing when you got this error?

**Comment by 1j01** [comment]
I'm not sure; I only looked and found the errors later.
But you can see from the code that it doesn't handle the case where the JSON isn't loaded yet.

**Comment by ijkilchenko** [comment]
Yes, perhaps it should fail more gracefully or there should be some kind of a delayed retry. 

Hey, if you are willing to figure out how to do so, I would joyfully merge your pull request and push it to the chrome extensions store.
